### PR TITLE
[libvpx] configure.sh erroneous make warnings starting with macOS 11.5.1

### LINKED ISSUE #1286: Erroneous libvpx make warnings starting with macOS 11.5.1
**Describe the bug**
_ld: warning: object file (libs/libvpx/libvpx.a(vpx_codec.c.o)) was built for newer macOS version (11.5) than being linked (11.0)_

macOS libvpx make warnings started due to Apple adding a modification level for the first time since 2001. Versions were "10.version.release" until Big Sur 11 which used "version.release": 11.r, 12.r, etc. On July 26 2021 Apple issued the first numbered security update adding .1 to 11.5 creating 11.5.1.

Libvpx configure passes a minimum version flag to make. PR #1253 eliminated annual libvpx maintenance by dropping the last .# leaving only the version. "10.version.release" became 10.version, 11.release became 11. Two days after the commit to master, the Apple change caused libvpx to pass "11.5" instead of "11".

**Changes**
libvpx configure.sh: If version starts with “10.” the last .# (Release) is dropped, 10.15.7 (10.v.r) becomes 10.15. Else the first period and everything after is truncated leaving only version: 11.5 and 11.5.1 become 11, 12.# and 12.#.# becomes 12, etc.

**Testing**
Tested on 10.14.6 Mojave, 10.15.7 Catalina, messages eliminated on 11.5.1 Big Sur.

Learning GitHub: I renamed the pull title from 10.5.1 to 11.5.1 but it deleted the pull request so added a second pull.

### PR DESCRIPTION
**Pull request by MarioG-X**
macOS libvpx only, fixes #1286. macOS added a modification level starting with 11.5.1 for security patches causing ibvpx make erroneous warning messages. Fix checks macOS 10, drops release; macOS 11+ drops digits after version number. Tested on 10.14.6 Mojave, 10.15.7 Catalina, 11.5, 11.5.1, 11.6 Big Sur.

### CODE REVIEW

**Review by andywolk — APPROVED** [review]

File: libs/libvpx/build/make/configure.sh [hunk 1]
```diff
@@ -865,7 +865,11 @@ process_common_toolchain() {
   case ${toolchain} in
     *-darwin-*)
       mvmin=$(sw_vers -productVersion)
-      mvmin="-mmacosx-version-min="${mvmin%.*}
+      if [[ $mvmin == 10.* ]]; then
```
Comment (gyzclw) [inline libs/libvpx/build/make/configure.sh:868]: m1 mac
